latitude = "38.9072N"
longitude = "77.0369W"

[engine_config]
max_depth = 12
people_per_sim = 100
min_tile_size = 40

[datasets]
population = "generate/datasets/sedac_population.tif"
terrain = "generate/datasets/esa_globcover.tif"
